# Generated by Django 4.1.4 on 2022-12-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Binyan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=15, verbose_name="Биньян")),
                ("name", models.CharField(max_length=15, verbose_name="Подгруппа")),
            ],
        ),
        migrations.CreateModel(
            name="Root",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, verbose_name="Подгруппа")),
                (
                    "picture",
                    models.URLField(
                        default="https://place-hold.it/300x200", verbose_name="Картинка"
                    ),
                ),
                (
                    "binyan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mycards.binyan",
                        verbose_name="Биньян с подгруппой",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, verbose_name="Часть речи")),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, verbose_name="Название (для поиска)"
                    ),
                ),
                (
                    "vocal_name",
                    models.CharField(
                        max_length=64, verbose_name="Название с огласовками"
                    ),
                ),
                ("exception", models.BooleanField(default=False)),
                (
                    "pronunciation",
                    models.CharField(max_length=64, verbose_name="Произношение"),
                ),
                (
                    "picture",
                    models.URLField(
                        default="https://place-hold.it/300x200", verbose_name="Картинка"
                    ),
                ),
                (
                    "translation",
                    models.CharField(max_length=64, verbose_name="Перевод"),
                ),
                ("example", models.TextField(null=True)),
                (
                    "root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="words",
                        to="mycards.root",
                        verbose_name="Корень",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mycards.type",
                        verbose_name="Часть речи",
                    ),
                ),
            ],
        ),
    ]
