# Generated by Django 4.1.4 on 2022-12-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0002_remove_root_binyan_remove_root_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="binyan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mycards.binyan",
                verbose_name="Биньян с подгруппой",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="root",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="words",
                to="mycards.root",
                verbose_name="Корень",
            ),
        ),
    ]
