# Generated by Django 4.1.4 on 2022-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0003_alter_word_binyan_alter_word_root"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="printed",
            field=models.BooleanField(default=False),
        ),
    ]
