# Generated by Django 4.1.4 on 2022-12-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mycards",
            "0005_remove_wordform_type_wordform_gender_wordform_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wordform",
            name="main_form",
            field=models.BooleanField(default=False),
        ),
    ]
