# Generated by Django 4.1.4 on 2022-12-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0006_wordform_main_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binyan",
            name="name",
            field=models.CharField(max_length=15, null=True, verbose_name="Подгруппа"),
        ),
    ]
