# Generated by Django 4.1.4 on 2022-12-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0007_alter_binyan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="grammema",
            field=models.CharField(default=1, max_length=4, verbose_name="Код"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Название"),
        ),
    ]
