# Generated by Django 4.1.4 on 2022-12-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0008_type_grammema_alter_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="example",
            field=models.CharField(default=1, max_length=25, verbose_name="Пример"),
            preserve_default=False,
        ),
    ]
