# Generated by Django 4.1.4 on 2022-12-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0009_type_example"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=25, verbose_name="Категория")),
                ("name", models.CharField(max_length=25, verbose_name="Название")),
            ],
        ),
        migrations.AddField(
            model_name="word",
            name="animacy",
            field=models.CharField(
                max_length=4, null=True, verbose_name="Одушевленность"
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="words",
                to="mycards.topic",
                verbose_name="Тема",
            ),
        ),
    ]
