# Generated by Django 4.1.4 on 2022-12-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0011_formtype_alter_wordform_exception_wordform_form_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=25, null=True, verbose_name="Название"),
        ),
    ]
