# Generated by Django 4.1.4 on 2023-01-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0016_alter_expression_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="question_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="mycards.expression",
                verbose_name="Номер вопроса",
            ),
        ),
    ]
