# Generated by Django 4.1.4 on 2023-01-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0018_alter_expression_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="comment",
            field=models.TextField(null=True),
        ),
    ]
