# Generated by Django 4.1.4 on 2023-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0019_expression_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="is_antonym",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
