# Generated by Django 4.1.4 on 2023-01-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0021_word_antonym_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="name_icon",
            field=models.CharField(max_length=25, null=True, verbose_name="Иконка"),
        ),
    ]
