# Generated by Django 4.1.4 on 2023-01-04 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0022_topic_name_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, verbose_name="Название категории"),
                ),
                (
                    "icon",
                    models.CharField(max_length=25, null=True, verbose_name="Иконка"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="mycards.category",
                        verbose_name="Родитель",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grouping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mycards.category",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mycards.word"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="word",
            name="categories",
            field=models.ManyToManyField(
                related_name="words", through="mycards.Grouping", to="mycards.category"
            ),
        ),
    ]
