# Generated by Django 4.1.4 on 2023-01-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0023_category_grouping_word_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="mycards.category",
                verbose_name="Родитель",
            ),
        ),
    ]
