# Generated by Django 4.1.4 on 2023-01-04 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0024_alter_category_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, verbose_name="Название класса"),
                ),
                (
                    "icon",
                    models.CharField(max_length=25, null=True, verbose_name="Иконка"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.AlterField(
            model_name="grouping",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mycards.category"
            ),
        ),
        migrations.AlterField(
            model_name="grouping",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mycards.word"
            ),
        ),
        migrations.CreateModel(
            name="Classifing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mycards.category",
                    ),
                ),
                (
                    "classes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mycards.classes",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="classes",
            field=models.ManyToManyField(
                related_name="categories",
                through="mycards.Classifing",
                to="mycards.classes",
            ),
        ),
    ]
