# Generated by Django 4.1.4 on 2023-01-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0025_classes_remove_category_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordform",
            name="comment",
            field=models.TextField(null=True),
        ),
    ]
