# Generated by Django 4.0.3 on 2023-01-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycards', '0026_wordform_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='binyan',
            name='output',
            field=models.CharField(max_length=4, null=True, verbose_name='Обозначение'),
        ),
    ]
