# Generated by Django 4.1.4 on 2023-01-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0028_word_time_create"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="word",
            options={
                "ordering": ["time_create", "name"],
                "verbose_name": "слово",
                "verbose_name_plural": "слово",
            },
        ),
        migrations.AlterField(
            model_name="word",
            name="animacy",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Одушевленность"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="antonym_word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="antonym",
                to="mycards.word",
                verbose_name="Антоним",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="binyan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mycards.binyan",
                verbose_name="Биньян с подгруппой",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="words",
                to="mycards.root",
                verbose_name="Корень",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="words",
                to="mycards.topic",
                verbose_name="Тема",
            ),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="example",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="gender",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
