# Generated by Django 4.1.4 on 2023-01-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0029_alter_word_options_alter_word_animacy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordform",
            name="gender",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="number",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
