# Generated by Django 4.1.4 on 2023-01-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0031_alter_word_animacy"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="word",
            constraint=models.UniqueConstraint(
                fields=("name", "picture"), name="unique_word"
            ),
        ),
        migrations.AlterModelTable(
            name="word",
            table="word",
        ),
    ]
