# Generated by Django 4.1.4 on 2023-01-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycards", "0032_word_unique_word_alter_word_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="word",
            name="unique_word",
        ),
        migrations.AddConstraint(
            model_name="word",
            constraint=models.UniqueConstraint(
                fields=("name", "picture"),
                name="unique_word",
                violation_error_message="Такое слово уже есть в базе данных",
            ),
        ),
    ]
