# Generated by Django 4.1.4 on 2023-05-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycards', '0035_alter_root_options_alter_root_name_alter_word_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='new_antonym',
            field=models.ManyToManyField(null=True, to='mycards.word'),
        ),
    ]
