# Generated by Django 4.1.4 on 2023-06-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycards', '0036_word_new_antonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20, verbose_name='Чат ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='ClientWordForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Выучено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycards.client')),
                ('wordform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycards.wordform')),
            ],
        ),
        migrations.AddField(
            model_name='wordform',
            name='client',
            field=models.ManyToManyField(related_name='words', through='mycards.ClientWordForm', to='mycards.client'),
        ),
    ]
